// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.26.1
// source: custom_events.proto

package genproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CustomEventsCreateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title       string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Date        string `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	Category    string `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
}

func (x *CustomEventsCreateReq) Reset() {
	*x = CustomEventsCreateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_custom_events_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomEventsCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomEventsCreateReq) ProtoMessage() {}

func (x *CustomEventsCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_custom_events_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomEventsCreateReq.ProtoReflect.Descriptor instead.
func (*CustomEventsCreateReq) Descriptor() ([]byte, []int) {
	return file_custom_events_proto_rawDescGZIP(), []int{0}
}

func (x *CustomEventsCreateReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CustomEventsCreateReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CustomEventsCreateReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CustomEventsCreateReq) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *CustomEventsCreateReq) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type CustomEventsUpdateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title       string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *CustomEventsUpdateReq) Reset() {
	*x = CustomEventsUpdateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_custom_events_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomEventsUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomEventsUpdateReq) ProtoMessage() {}

func (x *CustomEventsUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_custom_events_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomEventsUpdateReq.ProtoReflect.Descriptor instead.
func (*CustomEventsUpdateReq) Descriptor() ([]byte, []int) {
	return file_custom_events_proto_rawDescGZIP(), []int{1}
}

func (x *CustomEventsUpdateReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CustomEventsUpdateReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CustomEventsUpdateReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CustomEventsRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title       string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Date        string `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	Category    string `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	UserId      string `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *CustomEventsRes) Reset() {
	*x = CustomEventsRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_custom_events_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomEventsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomEventsRes) ProtoMessage() {}

func (x *CustomEventsRes) ProtoReflect() protoreflect.Message {
	mi := &file_custom_events_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomEventsRes.ProtoReflect.Descriptor instead.
func (*CustomEventsRes) Descriptor() ([]byte, []int) {
	return file_custom_events_proto_rawDescGZIP(), []int{2}
}

func (x *CustomEventsRes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CustomEventsRes) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CustomEventsRes) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CustomEventsRes) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *CustomEventsRes) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CustomEventsRes) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CustomEventsGetByIdRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Event *CustomEventsRes `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
}

func (x *CustomEventsGetByIdRes) Reset() {
	*x = CustomEventsGetByIdRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_custom_events_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomEventsGetByIdRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomEventsGetByIdRes) ProtoMessage() {}

func (x *CustomEventsGetByIdRes) ProtoReflect() protoreflect.Message {
	mi := &file_custom_events_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomEventsGetByIdRes.ProtoReflect.Descriptor instead.
func (*CustomEventsGetByIdRes) Descriptor() ([]byte, []int) {
	return file_custom_events_proto_rawDescGZIP(), []int{3}
}

func (x *CustomEventsGetByIdRes) GetEvent() *CustomEventsRes {
	if x != nil {
		return x.Event
	}
	return nil
}

type CustomEventsGetAllRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Events []*CustomEventsRes `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	Count  int32              `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *CustomEventsGetAllRes) Reset() {
	*x = CustomEventsGetAllRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_custom_events_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomEventsGetAllRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomEventsGetAllRes) ProtoMessage() {}

func (x *CustomEventsGetAllRes) ProtoReflect() protoreflect.Message {
	mi := &file_custom_events_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomEventsGetAllRes.ProtoReflect.Descriptor instead.
func (*CustomEventsGetAllRes) Descriptor() ([]byte, []int) {
	return file_custom_events_proto_rawDescGZIP(), []int{4}
}

func (x *CustomEventsGetAllRes) GetEvents() []*CustomEventsRes {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *CustomEventsGetAllRes) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type CustomEventsGetAllReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string  `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Filter *Filter `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
}

func (x *CustomEventsGetAllReq) Reset() {
	*x = CustomEventsGetAllReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_custom_events_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomEventsGetAllReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomEventsGetAllReq) ProtoMessage() {}

func (x *CustomEventsGetAllReq) ProtoReflect() protoreflect.Message {
	mi := &file_custom_events_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomEventsGetAllReq.ProtoReflect.Descriptor instead.
func (*CustomEventsGetAllReq) Descriptor() ([]byte, []int) {
	return file_custom_events_proto_rawDescGZIP(), []int{5}
}

func (x *CustomEventsGetAllReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CustomEventsGetAllReq) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

var File_custom_events_proto protoreflect.FileDescriptor

var file_custom_events_proto_rawDesc = []byte{
	0x0a, 0x13, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x63, 0x61, 0x70, 0x73,
	0x75, 0x6c, 0x65, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x98, 0x01, 0x0a, 0x15, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x22, 0x5f, 0x0a, 0x15,
	0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xa2, 0x01,
	0x0a, 0x0f, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65,
	0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x22, 0x4d, 0x0a, 0x16, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x73, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x12, 0x33, 0x0a, 0x05,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x74, 0x69,
	0x6d, 0x65, 0x5f, 0x63, 0x61, 0x70, 0x73, 0x75, 0x6c, 0x65, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x22, 0x64, 0x0a, 0x15, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x12, 0x35, 0x0a, 0x06, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x74, 0x69, 0x6d,
	0x65, 0x5f, 0x63, 0x61, 0x70, 0x73, 0x75, 0x6c, 0x65, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x52, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x5e, 0x0a, 0x15, 0x43, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x06, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x74, 0x69, 0x6d, 0x65,
	0x5f, 0x63, 0x61, 0x70, 0x73, 0x75, 0x6c, 0x65, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52,
	0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x32, 0xe6, 0x02, 0x0a, 0x13, 0x43, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x41, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x23, 0x2e, 0x74, 0x69, 0x6d, 0x65,
	0x5f, 0x63, 0x61, 0x70, 0x73, 0x75, 0x6c, 0x65, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x12,
	0x2e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x63, 0x61, 0x70, 0x73, 0x75, 0x6c, 0x65, 0x2e, 0x56, 0x6f,
	0x69, 0x64, 0x12, 0x43, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x12, 0x12, 0x2e,
	0x74, 0x69, 0x6d, 0x65, 0x5f, 0x63, 0x61, 0x70, 0x73, 0x75, 0x6c, 0x65, 0x2e, 0x42, 0x79, 0x49,
	0x64, 0x1a, 0x24, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x63, 0x61, 0x70, 0x73, 0x75, 0x6c, 0x65,
	0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x47, 0x65, 0x74,
	0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x12, 0x52, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x12, 0x23, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x63, 0x61, 0x70, 0x73, 0x75, 0x6c, 0x65,
	0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x23, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x63, 0x61,
	0x70, 0x73, 0x75, 0x6c, 0x65, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x73, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x12, 0x41, 0x0a, 0x06, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x23, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x63, 0x61, 0x70,
	0x73, 0x75, 0x6c, 0x65, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x74, 0x69, 0x6d,
	0x65, 0x5f, 0x63, 0x61, 0x70, 0x73, 0x75, 0x6c, 0x65, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x12, 0x30,
	0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x12, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x5f,
	0x63, 0x61, 0x70, 0x73, 0x75, 0x6c, 0x65, 0x2e, 0x42, 0x79, 0x49, 0x64, 0x1a, 0x12, 0x2e, 0x74,
	0x69, 0x6d, 0x65, 0x5f, 0x63, 0x61, 0x70, 0x73, 0x75, 0x6c, 0x65, 0x2e, 0x56, 0x6f, 0x69, 0x64,
	0x42, 0x0b, 0x5a, 0x09, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_custom_events_proto_rawDescOnce sync.Once
	file_custom_events_proto_rawDescData = file_custom_events_proto_rawDesc
)

func file_custom_events_proto_rawDescGZIP() []byte {
	file_custom_events_proto_rawDescOnce.Do(func() {
		file_custom_events_proto_rawDescData = protoimpl.X.CompressGZIP(file_custom_events_proto_rawDescData)
	})
	return file_custom_events_proto_rawDescData
}

var file_custom_events_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_custom_events_proto_goTypes = []interface{}{
	(*CustomEventsCreateReq)(nil),  // 0: time_capsule.CustomEventsCreateReq
	(*CustomEventsUpdateReq)(nil),  // 1: time_capsule.CustomEventsUpdateReq
	(*CustomEventsRes)(nil),        // 2: time_capsule.CustomEventsRes
	(*CustomEventsGetByIdRes)(nil), // 3: time_capsule.CustomEventsGetByIdRes
	(*CustomEventsGetAllRes)(nil),  // 4: time_capsule.CustomEventsGetAllRes
	(*CustomEventsGetAllReq)(nil),  // 5: time_capsule.CustomEventsGetAllReq
	(*Filter)(nil),                 // 6: time_capsule.Filter
	(*ById)(nil),                   // 7: time_capsule.ById
	(*Void)(nil),                   // 8: time_capsule.Void
}
var file_custom_events_proto_depIdxs = []int32{
	2, // 0: time_capsule.CustomEventsGetByIdRes.event:type_name -> time_capsule.CustomEventsRes
	2, // 1: time_capsule.CustomEventsGetAllRes.events:type_name -> time_capsule.CustomEventsRes
	6, // 2: time_capsule.CustomEventsGetAllReq.filter:type_name -> time_capsule.Filter
	0, // 3: time_capsule.CustomEventsService.Create:input_type -> time_capsule.CustomEventsCreateReq
	7, // 4: time_capsule.CustomEventsService.GetById:input_type -> time_capsule.ById
	5, // 5: time_capsule.CustomEventsService.GetAll:input_type -> time_capsule.CustomEventsGetAllReq
	1, // 6: time_capsule.CustomEventsService.Update:input_type -> time_capsule.CustomEventsUpdateReq
	7, // 7: time_capsule.CustomEventsService.Delete:input_type -> time_capsule.ById
	8, // 8: time_capsule.CustomEventsService.Create:output_type -> time_capsule.Void
	3, // 9: time_capsule.CustomEventsService.GetById:output_type -> time_capsule.CustomEventsGetByIdRes
	4, // 10: time_capsule.CustomEventsService.GetAll:output_type -> time_capsule.CustomEventsGetAllRes
	8, // 11: time_capsule.CustomEventsService.Update:output_type -> time_capsule.Void
	8, // 12: time_capsule.CustomEventsService.Delete:output_type -> time_capsule.Void
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_custom_events_proto_init() }
func file_custom_events_proto_init() {
	if File_custom_events_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_custom_events_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomEventsCreateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_custom_events_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomEventsUpdateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_custom_events_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomEventsRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_custom_events_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomEventsGetByIdRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_custom_events_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomEventsGetAllRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_custom_events_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomEventsGetAllReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_custom_events_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_custom_events_proto_goTypes,
		DependencyIndexes: file_custom_events_proto_depIdxs,
		MessageInfos:      file_custom_events_proto_msgTypes,
	}.Build()
	File_custom_events_proto = out.File
	file_custom_events_proto_rawDesc = nil
	file_custom_events_proto_goTypes = nil
	file_custom_events_proto_depIdxs = nil
}
