// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.26.1
// source: medias.proto

package genproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MediasCreateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MemoryId string `protobuf:"bytes,1,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
	Type     string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Url      string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *MediasCreateReq) Reset() {
	*x = MediasCreateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_medias_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MediasCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediasCreateReq) ProtoMessage() {}

func (x *MediasCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_medias_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediasCreateReq.ProtoReflect.Descriptor instead.
func (*MediasCreateReq) Descriptor() ([]byte, []int) {
	return file_medias_proto_rawDescGZIP(), []int{0}
}

func (x *MediasCreateReq) GetMemoryId() string {
	if x != nil {
		return x.MemoryId
	}
	return ""
}

func (x *MediasCreateReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MediasCreateReq) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type MediasUpdateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Url  string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *MediasUpdateReq) Reset() {
	*x = MediasUpdateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_medias_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MediasUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediasUpdateReq) ProtoMessage() {}

func (x *MediasUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_medias_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediasUpdateReq.ProtoReflect.Descriptor instead.
func (*MediasUpdateReq) Descriptor() ([]byte, []int) {
	return file_medias_proto_rawDescGZIP(), []int{1}
}

func (x *MediasUpdateReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MediasUpdateReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MediasUpdateReq) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type MediasRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type     string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Url      string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Date     string `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	MemoryId string `protobuf:"bytes,5,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
}

func (x *MediasRes) Reset() {
	*x = MediasRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_medias_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MediasRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediasRes) ProtoMessage() {}

func (x *MediasRes) ProtoReflect() protoreflect.Message {
	mi := &file_medias_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediasRes.ProtoReflect.Descriptor instead.
func (*MediasRes) Descriptor() ([]byte, []int) {
	return file_medias_proto_rawDescGZIP(), []int{2}
}

func (x *MediasRes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MediasRes) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MediasRes) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *MediasRes) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *MediasRes) GetMemoryId() string {
	if x != nil {
		return x.MemoryId
	}
	return ""
}

type MediasGetByIdRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Media *MediasRes `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
}

func (x *MediasGetByIdRes) Reset() {
	*x = MediasGetByIdRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_medias_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MediasGetByIdRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediasGetByIdRes) ProtoMessage() {}

func (x *MediasGetByIdRes) ProtoReflect() protoreflect.Message {
	mi := &file_medias_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediasGetByIdRes.ProtoReflect.Descriptor instead.
func (*MediasGetByIdRes) Descriptor() ([]byte, []int) {
	return file_medias_proto_rawDescGZIP(), []int{3}
}

func (x *MediasGetByIdRes) GetMedia() *MediasRes {
	if x != nil {
		return x.Media
	}
	return nil
}

type MediasGetAllRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Medias []*MediasRes `protobuf:"bytes,1,rep,name=medias,proto3" json:"medias,omitempty"`
	Count  int32        `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *MediasGetAllRes) Reset() {
	*x = MediasGetAllRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_medias_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MediasGetAllRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediasGetAllRes) ProtoMessage() {}

func (x *MediasGetAllRes) ProtoReflect() protoreflect.Message {
	mi := &file_medias_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediasGetAllRes.ProtoReflect.Descriptor instead.
func (*MediasGetAllRes) Descriptor() ([]byte, []int) {
	return file_medias_proto_rawDescGZIP(), []int{4}
}

func (x *MediasGetAllRes) GetMedias() []*MediasRes {
	if x != nil {
		return x.Medias
	}
	return nil
}

func (x *MediasGetAllRes) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type MediasGetAllReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MemoryId string  `protobuf:"bytes,1,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
	Filter   *Filter `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
}

func (x *MediasGetAllReq) Reset() {
	*x = MediasGetAllReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_medias_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MediasGetAllReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediasGetAllReq) ProtoMessage() {}

func (x *MediasGetAllReq) ProtoReflect() protoreflect.Message {
	mi := &file_medias_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediasGetAllReq.ProtoReflect.Descriptor instead.
func (*MediasGetAllReq) Descriptor() ([]byte, []int) {
	return file_medias_proto_rawDescGZIP(), []int{5}
}

func (x *MediasGetAllReq) GetMemoryId() string {
	if x != nil {
		return x.MemoryId
	}
	return ""
}

func (x *MediasGetAllReq) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

var File_medias_proto protoreflect.FileDescriptor

var file_medias_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c,
	0x74, 0x69, 0x6d, 0x65, 0x5f, 0x63, 0x61, 0x70, 0x73, 0x75, 0x6c, 0x65, 0x1a, 0x0c, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x54, 0x0a, 0x0f, 0x4d, 0x65,
	0x64, 0x69, 0x61, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a,
	0x09, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c,
	0x22, 0x47, 0x0a, 0x0f, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x72, 0x0a, 0x09, 0x4d, 0x65, 0x64,
	0x69, 0x61, 0x73, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72,
	0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x22, 0x41, 0x0a,
	0x10, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x73, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65,
	0x73, 0x12, 0x2d, 0x0a, 0x05, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x63, 0x61, 0x70, 0x73, 0x75, 0x6c, 0x65, 0x2e,
	0x4d, 0x65, 0x64, 0x69, 0x61, 0x73, 0x52, 0x65, 0x73, 0x52, 0x05, 0x6d, 0x65, 0x64, 0x69, 0x61,
	0x22, 0x58, 0x0a, 0x0f, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x73, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x52, 0x65, 0x73, 0x12, 0x2f, 0x0a, 0x06, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x63, 0x61, 0x70, 0x73, 0x75,
	0x6c, 0x65, 0x2e, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x73, 0x52, 0x65, 0x73, 0x52, 0x06, 0x6d, 0x65,
	0x64, 0x69, 0x61, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x5c, 0x0a, 0x0f, 0x4d, 0x65,
	0x64, 0x69, 0x61, 0x73, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a,
	0x09, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x06, 0x66, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x74, 0x69, 0x6d,
	0x65, 0x5f, 0x63, 0x61, 0x70, 0x73, 0x75, 0x6c, 0x65, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x32, 0xc2, 0x02, 0x0a, 0x0d, 0x4d, 0x65, 0x64,
	0x69, 0x61, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3b, 0x0a, 0x06, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x12, 0x1d, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x63, 0x61, 0x70, 0x73,
	0x75, 0x6c, 0x65, 0x2e, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x63, 0x61, 0x70, 0x73, 0x75,
	0x6c, 0x65, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x12, 0x3d, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x42, 0x79,
	0x49, 0x64, 0x12, 0x12, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x63, 0x61, 0x70, 0x73, 0x75, 0x6c,
	0x65, 0x2e, 0x42, 0x79, 0x49, 0x64, 0x1a, 0x1e, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x63, 0x61,
	0x70, 0x73, 0x75, 0x6c, 0x65, 0x2e, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x73, 0x47, 0x65, 0x74, 0x42,
	0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x12, 0x46, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x12, 0x1d, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x63, 0x61, 0x70, 0x73, 0x75, 0x6c, 0x65, 0x2e,
	0x4d, 0x65, 0x64, 0x69, 0x61, 0x73, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x1a,
	0x1d, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x63, 0x61, 0x70, 0x73, 0x75, 0x6c, 0x65, 0x2e, 0x4d,
	0x65, 0x64, 0x69, 0x61, 0x73, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x12, 0x3b,
	0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1d, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x5f,
	0x63, 0x61, 0x70, 0x73, 0x75, 0x6c, 0x65, 0x2e, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x73, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x63,
	0x61, 0x70, 0x73, 0x75, 0x6c, 0x65, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x12, 0x30, 0x0a, 0x06, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x12, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x63, 0x61, 0x70,
	0x73, 0x75, 0x6c, 0x65, 0x2e, 0x42, 0x79, 0x49, 0x64, 0x1a, 0x12, 0x2e, 0x74, 0x69, 0x6d, 0x65,
	0x5f, 0x63, 0x61, 0x70, 0x73, 0x75, 0x6c, 0x65, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x42, 0x0b, 0x5a,
	0x09, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_medias_proto_rawDescOnce sync.Once
	file_medias_proto_rawDescData = file_medias_proto_rawDesc
)

func file_medias_proto_rawDescGZIP() []byte {
	file_medias_proto_rawDescOnce.Do(func() {
		file_medias_proto_rawDescData = protoimpl.X.CompressGZIP(file_medias_proto_rawDescData)
	})
	return file_medias_proto_rawDescData
}

var file_medias_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_medias_proto_goTypes = []interface{}{
	(*MediasCreateReq)(nil),  // 0: time_capsule.MediasCreateReq
	(*MediasUpdateReq)(nil),  // 1: time_capsule.MediasUpdateReq
	(*MediasRes)(nil),        // 2: time_capsule.MediasRes
	(*MediasGetByIdRes)(nil), // 3: time_capsule.MediasGetByIdRes
	(*MediasGetAllRes)(nil),  // 4: time_capsule.MediasGetAllRes
	(*MediasGetAllReq)(nil),  // 5: time_capsule.MediasGetAllReq
	(*Filter)(nil),           // 6: time_capsule.Filter
	(*ById)(nil),             // 7: time_capsule.ById
	(*Void)(nil),             // 8: time_capsule.Void
}
var file_medias_proto_depIdxs = []int32{
	2, // 0: time_capsule.MediasGetByIdRes.media:type_name -> time_capsule.MediasRes
	2, // 1: time_capsule.MediasGetAllRes.medias:type_name -> time_capsule.MediasRes
	6, // 2: time_capsule.MediasGetAllReq.filter:type_name -> time_capsule.Filter
	0, // 3: time_capsule.MediasService.Create:input_type -> time_capsule.MediasCreateReq
	7, // 4: time_capsule.MediasService.GetById:input_type -> time_capsule.ById
	5, // 5: time_capsule.MediasService.GetAll:input_type -> time_capsule.MediasGetAllReq
	1, // 6: time_capsule.MediasService.Update:input_type -> time_capsule.MediasUpdateReq
	7, // 7: time_capsule.MediasService.Delete:input_type -> time_capsule.ById
	8, // 8: time_capsule.MediasService.Create:output_type -> time_capsule.Void
	3, // 9: time_capsule.MediasService.GetById:output_type -> time_capsule.MediasGetByIdRes
	4, // 10: time_capsule.MediasService.GetAll:output_type -> time_capsule.MediasGetAllRes
	8, // 11: time_capsule.MediasService.Update:output_type -> time_capsule.Void
	8, // 12: time_capsule.MediasService.Delete:output_type -> time_capsule.Void
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_medias_proto_init() }
func file_medias_proto_init() {
	if File_medias_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_medias_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MediasCreateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_medias_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MediasUpdateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_medias_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MediasRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_medias_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MediasGetByIdRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_medias_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MediasGetAllRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_medias_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MediasGetAllReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_medias_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_medias_proto_goTypes,
		DependencyIndexes: file_medias_proto_depIdxs,
		MessageInfos:      file_medias_proto_msgTypes,
	}.Build()
	File_medias_proto = out.File
	file_medias_proto_rawDesc = nil
	file_medias_proto_goTypes = nil
	file_medias_proto_depIdxs = nil
}
