// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: memories.proto

package genproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MemoriesService_Create_FullMethodName  = "/time_capsule.MemoriesService/Create"
	MemoriesService_GetById_FullMethodName = "/time_capsule.MemoriesService/GetById"
	MemoriesService_GetAll_FullMethodName  = "/time_capsule.MemoriesService/GetAll"
	MemoriesService_Update_FullMethodName  = "/time_capsule.MemoriesService/Update"
	MemoriesService_Delete_FullMethodName  = "/time_capsule.MemoriesService/Delete"
)

// MemoriesServiceClient is the client API for MemoriesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MemoriesServiceClient interface {
	Create(ctx context.Context, in *MemoriesCreateReq, opts ...grpc.CallOption) (*Void, error)
	GetById(ctx context.Context, in *ById, opts ...grpc.CallOption) (*MemoriesGetByIdRes, error)
	GetAll(ctx context.Context, in *MemoriesGetAllReq, opts ...grpc.CallOption) (*MemoriesGetAllRes, error)
	Update(ctx context.Context, in *MemoriesUpdateReq, opts ...grpc.CallOption) (*Void, error)
	Delete(ctx context.Context, in *ById, opts ...grpc.CallOption) (*Void, error)
}

type memoriesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMemoriesServiceClient(cc grpc.ClientConnInterface) MemoriesServiceClient {
	return &memoriesServiceClient{cc}
}

func (c *memoriesServiceClient) Create(ctx context.Context, in *MemoriesCreateReq, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, MemoriesService_Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoriesServiceClient) GetById(ctx context.Context, in *ById, opts ...grpc.CallOption) (*MemoriesGetByIdRes, error) {
	out := new(MemoriesGetByIdRes)
	err := c.cc.Invoke(ctx, MemoriesService_GetById_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoriesServiceClient) GetAll(ctx context.Context, in *MemoriesGetAllReq, opts ...grpc.CallOption) (*MemoriesGetAllRes, error) {
	out := new(MemoriesGetAllRes)
	err := c.cc.Invoke(ctx, MemoriesService_GetAll_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoriesServiceClient) Update(ctx context.Context, in *MemoriesUpdateReq, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, MemoriesService_Update_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoriesServiceClient) Delete(ctx context.Context, in *ById, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, MemoriesService_Delete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MemoriesServiceServer is the server API for MemoriesService service.
// All implementations must embed UnimplementedMemoriesServiceServer
// for forward compatibility
type MemoriesServiceServer interface {
	Create(context.Context, *MemoriesCreateReq) (*Void, error)
	GetById(context.Context, *ById) (*MemoriesGetByIdRes, error)
	GetAll(context.Context, *MemoriesGetAllReq) (*MemoriesGetAllRes, error)
	Update(context.Context, *MemoriesUpdateReq) (*Void, error)
	Delete(context.Context, *ById) (*Void, error)
	mustEmbedUnimplementedMemoriesServiceServer()
}

// UnimplementedMemoriesServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMemoriesServiceServer struct {
}

func (UnimplementedMemoriesServiceServer) Create(context.Context, *MemoriesCreateReq) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedMemoriesServiceServer) GetById(context.Context, *ById) (*MemoriesGetByIdRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetById not implemented")
}
func (UnimplementedMemoriesServiceServer) GetAll(context.Context, *MemoriesGetAllReq) (*MemoriesGetAllRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedMemoriesServiceServer) Update(context.Context, *MemoriesUpdateReq) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedMemoriesServiceServer) Delete(context.Context, *ById) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedMemoriesServiceServer) mustEmbedUnimplementedMemoriesServiceServer() {}

// UnsafeMemoriesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MemoriesServiceServer will
// result in compilation errors.
type UnsafeMemoriesServiceServer interface {
	mustEmbedUnimplementedMemoriesServiceServer()
}

func RegisterMemoriesServiceServer(s grpc.ServiceRegistrar, srv MemoriesServiceServer) {
	s.RegisterService(&MemoriesService_ServiceDesc, srv)
}

func _MemoriesService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemoriesCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoriesServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoriesService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoriesServiceServer).Create(ctx, req.(*MemoriesCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoriesService_GetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoriesServiceServer).GetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoriesService_GetById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoriesServiceServer).GetById(ctx, req.(*ById))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoriesService_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemoriesGetAllReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoriesServiceServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoriesService_GetAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoriesServiceServer).GetAll(ctx, req.(*MemoriesGetAllReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoriesService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemoriesUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoriesServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoriesService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoriesServiceServer).Update(ctx, req.(*MemoriesUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoriesService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoriesServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoriesService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoriesServiceServer).Delete(ctx, req.(*ById))
	}
	return interceptor(ctx, in, info, handler)
}

// MemoriesService_ServiceDesc is the grpc.ServiceDesc for MemoriesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MemoriesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "time_capsule.MemoriesService",
	HandlerType: (*MemoriesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _MemoriesService_Create_Handler,
		},
		{
			MethodName: "GetById",
			Handler:    _MemoriesService_GetById_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _MemoriesService_GetAll_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _MemoriesService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _MemoriesService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "memories.proto",
}
