// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.26.1
// source: milestones.proto

package genproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MilestonesCreateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title    string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Date     string `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	Category string `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
}

func (x *MilestonesCreateReq) Reset() {
	*x = MilestonesCreateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_milestones_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MilestonesCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MilestonesCreateReq) ProtoMessage() {}

func (x *MilestonesCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_milestones_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MilestonesCreateReq.ProtoReflect.Descriptor instead.
func (*MilestonesCreateReq) Descriptor() ([]byte, []int) {
	return file_milestones_proto_rawDescGZIP(), []int{0}
}

func (x *MilestonesCreateReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MilestonesCreateReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MilestonesCreateReq) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *MilestonesCreateReq) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type MilestonesUpdateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Date  string `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
}

func (x *MilestonesUpdateReq) Reset() {
	*x = MilestonesUpdateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_milestones_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MilestonesUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MilestonesUpdateReq) ProtoMessage() {}

func (x *MilestonesUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_milestones_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MilestonesUpdateReq.ProtoReflect.Descriptor instead.
func (*MilestonesUpdateReq) Descriptor() ([]byte, []int) {
	return file_milestones_proto_rawDescGZIP(), []int{1}
}

func (x *MilestonesUpdateReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MilestonesUpdateReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MilestonesUpdateReq) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type MilestonesRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title    string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Date     string `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	Category string `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	UserId   string `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *MilestonesRes) Reset() {
	*x = MilestonesRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_milestones_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MilestonesRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MilestonesRes) ProtoMessage() {}

func (x *MilestonesRes) ProtoReflect() protoreflect.Message {
	mi := &file_milestones_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MilestonesRes.ProtoReflect.Descriptor instead.
func (*MilestonesRes) Descriptor() ([]byte, []int) {
	return file_milestones_proto_rawDescGZIP(), []int{2}
}

func (x *MilestonesRes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MilestonesRes) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MilestonesRes) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *MilestonesRes) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *MilestonesRes) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type MilestonesGetByIdRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Milestone *MilestonesRes `protobuf:"bytes,1,opt,name=milestone,proto3" json:"milestone,omitempty"`
}

func (x *MilestonesGetByIdRes) Reset() {
	*x = MilestonesGetByIdRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_milestones_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MilestonesGetByIdRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MilestonesGetByIdRes) ProtoMessage() {}

func (x *MilestonesGetByIdRes) ProtoReflect() protoreflect.Message {
	mi := &file_milestones_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MilestonesGetByIdRes.ProtoReflect.Descriptor instead.
func (*MilestonesGetByIdRes) Descriptor() ([]byte, []int) {
	return file_milestones_proto_rawDescGZIP(), []int{3}
}

func (x *MilestonesGetByIdRes) GetMilestone() *MilestonesRes {
	if x != nil {
		return x.Milestone
	}
	return nil
}

type MilestonesGetAllRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Milestones []*MilestonesRes `protobuf:"bytes,1,rep,name=milestones,proto3" json:"milestones,omitempty"`
	Count      int32            `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *MilestonesGetAllRes) Reset() {
	*x = MilestonesGetAllRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_milestones_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MilestonesGetAllRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MilestonesGetAllRes) ProtoMessage() {}

func (x *MilestonesGetAllRes) ProtoReflect() protoreflect.Message {
	mi := &file_milestones_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MilestonesGetAllRes.ProtoReflect.Descriptor instead.
func (*MilestonesGetAllRes) Descriptor() ([]byte, []int) {
	return file_milestones_proto_rawDescGZIP(), []int{4}
}

func (x *MilestonesGetAllRes) GetMilestones() []*MilestonesRes {
	if x != nil {
		return x.Milestones
	}
	return nil
}

func (x *MilestonesGetAllRes) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type MilestonesGetAllReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string  `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Filter *Filter `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
}

func (x *MilestonesGetAllReq) Reset() {
	*x = MilestonesGetAllReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_milestones_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MilestonesGetAllReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MilestonesGetAllReq) ProtoMessage() {}

func (x *MilestonesGetAllReq) ProtoReflect() protoreflect.Message {
	mi := &file_milestones_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MilestonesGetAllReq.ProtoReflect.Descriptor instead.
func (*MilestonesGetAllReq) Descriptor() ([]byte, []int) {
	return file_milestones_proto_rawDescGZIP(), []int{5}
}

func (x *MilestonesGetAllReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MilestonesGetAllReq) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

var File_milestones_proto protoreflect.FileDescriptor

var file_milestones_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6d, 0x69, 0x6c, 0x65, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0c, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x63, 0x61, 0x70, 0x73, 0x75, 0x6c, 0x65,
	0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x74,
	0x0a, 0x13, 0x4d, 0x69, 0x6c, 0x65, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x73, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x22, 0x4f, 0x0a, 0x13, 0x4d, 0x69, 0x6c, 0x65, 0x73, 0x74, 0x6f, 0x6e,
	0x65, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x65, 0x22, 0x7e, 0x0a, 0x0d, 0x4d, 0x69, 0x6c, 0x65, 0x73, 0x74, 0x6f,
	0x6e, 0x65, 0x73, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x51, 0x0a, 0x14, 0x4d, 0x69, 0x6c, 0x65, 0x73, 0x74, 0x6f,
	0x6e, 0x65, 0x73, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x12, 0x39, 0x0a,
	0x09, 0x6d, 0x69, 0x6c, 0x65, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x63, 0x61, 0x70, 0x73, 0x75, 0x6c, 0x65, 0x2e,
	0x4d, 0x69, 0x6c, 0x65, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x73, 0x52, 0x65, 0x73, 0x52, 0x09, 0x6d,
	0x69, 0x6c, 0x65, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x22, 0x68, 0x0a, 0x13, 0x4d, 0x69, 0x6c, 0x65,
	0x73, 0x74, 0x6f, 0x6e, 0x65, 0x73, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x12,
	0x3b, 0x0a, 0x0a, 0x6d, 0x69, 0x6c, 0x65, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x63, 0x61, 0x70, 0x73, 0x75,
	0x6c, 0x65, 0x2e, 0x4d, 0x69, 0x6c, 0x65, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x52, 0x0a, 0x6d, 0x69, 0x6c, 0x65, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x22, 0x5c, 0x0a, 0x13, 0x4d, 0x69, 0x6c, 0x65, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x73,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x2c, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x63, 0x61, 0x70, 0x73, 0x75, 0x6c,
	0x65, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x32, 0xda, 0x02, 0x0a, 0x11, 0x4d, 0x69, 0x6c, 0x65, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x73, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3f, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x12, 0x21, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x63, 0x61, 0x70, 0x73, 0x75, 0x6c, 0x65, 0x2e,
	0x4d, 0x69, 0x6c, 0x65, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x63, 0x61, 0x70, 0x73, 0x75,
	0x6c, 0x65, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x12, 0x41, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x42, 0x79,
	0x49, 0x64, 0x12, 0x12, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x63, 0x61, 0x70, 0x73, 0x75, 0x6c,
	0x65, 0x2e, 0x42, 0x79, 0x49, 0x64, 0x1a, 0x22, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x63, 0x61,
	0x70, 0x73, 0x75, 0x6c, 0x65, 0x2e, 0x4d, 0x69, 0x6c, 0x65, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x73,
	0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x12, 0x4e, 0x0a, 0x06, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x6c, 0x12, 0x21, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x63, 0x61, 0x70, 0x73,
	0x75, 0x6c, 0x65, 0x2e, 0x4d, 0x69, 0x6c, 0x65, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x73, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x21, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x63,
	0x61, 0x70, 0x73, 0x75, 0x6c, 0x65, 0x2e, 0x4d, 0x69, 0x6c, 0x65, 0x73, 0x74, 0x6f, 0x6e, 0x65,
	0x73, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x12, 0x3f, 0x0a, 0x06, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x12, 0x21, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x63, 0x61, 0x70, 0x73,
	0x75, 0x6c, 0x65, 0x2e, 0x4d, 0x69, 0x6c, 0x65, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x73, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x63,
	0x61, 0x70, 0x73, 0x75, 0x6c, 0x65, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x12, 0x30, 0x0a, 0x06, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x12, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x63, 0x61, 0x70,
	0x73, 0x75, 0x6c, 0x65, 0x2e, 0x42, 0x79, 0x49, 0x64, 0x1a, 0x12, 0x2e, 0x74, 0x69, 0x6d, 0x65,
	0x5f, 0x63, 0x61, 0x70, 0x73, 0x75, 0x6c, 0x65, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x42, 0x0b, 0x5a,
	0x09, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_milestones_proto_rawDescOnce sync.Once
	file_milestones_proto_rawDescData = file_milestones_proto_rawDesc
)

func file_milestones_proto_rawDescGZIP() []byte {
	file_milestones_proto_rawDescOnce.Do(func() {
		file_milestones_proto_rawDescData = protoimpl.X.CompressGZIP(file_milestones_proto_rawDescData)
	})
	return file_milestones_proto_rawDescData
}

var file_milestones_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_milestones_proto_goTypes = []interface{}{
	(*MilestonesCreateReq)(nil),  // 0: time_capsule.MilestonesCreateReq
	(*MilestonesUpdateReq)(nil),  // 1: time_capsule.MilestonesUpdateReq
	(*MilestonesRes)(nil),        // 2: time_capsule.MilestonesRes
	(*MilestonesGetByIdRes)(nil), // 3: time_capsule.MilestonesGetByIdRes
	(*MilestonesGetAllRes)(nil),  // 4: time_capsule.MilestonesGetAllRes
	(*MilestonesGetAllReq)(nil),  // 5: time_capsule.MilestonesGetAllReq
	(*Filter)(nil),               // 6: time_capsule.Filter
	(*ById)(nil),                 // 7: time_capsule.ById
	(*Void)(nil),                 // 8: time_capsule.Void
}
var file_milestones_proto_depIdxs = []int32{
	2, // 0: time_capsule.MilestonesGetByIdRes.milestone:type_name -> time_capsule.MilestonesRes
	2, // 1: time_capsule.MilestonesGetAllRes.milestones:type_name -> time_capsule.MilestonesRes
	6, // 2: time_capsule.MilestonesGetAllReq.filter:type_name -> time_capsule.Filter
	0, // 3: time_capsule.MilestonesService.Create:input_type -> time_capsule.MilestonesCreateReq
	7, // 4: time_capsule.MilestonesService.GetById:input_type -> time_capsule.ById
	5, // 5: time_capsule.MilestonesService.GetAll:input_type -> time_capsule.MilestonesGetAllReq
	1, // 6: time_capsule.MilestonesService.Update:input_type -> time_capsule.MilestonesUpdateReq
	7, // 7: time_capsule.MilestonesService.Delete:input_type -> time_capsule.ById
	8, // 8: time_capsule.MilestonesService.Create:output_type -> time_capsule.Void
	3, // 9: time_capsule.MilestonesService.GetById:output_type -> time_capsule.MilestonesGetByIdRes
	4, // 10: time_capsule.MilestonesService.GetAll:output_type -> time_capsule.MilestonesGetAllRes
	8, // 11: time_capsule.MilestonesService.Update:output_type -> time_capsule.Void
	8, // 12: time_capsule.MilestonesService.Delete:output_type -> time_capsule.Void
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_milestones_proto_init() }
func file_milestones_proto_init() {
	if File_milestones_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_milestones_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MilestonesCreateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_milestones_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MilestonesUpdateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_milestones_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MilestonesRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_milestones_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MilestonesGetByIdRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_milestones_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MilestonesGetAllRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_milestones_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MilestonesGetAllReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_milestones_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_milestones_proto_goTypes,
		DependencyIndexes: file_milestones_proto_depIdxs,
		MessageInfos:      file_milestones_proto_msgTypes,
	}.Build()
	File_milestones_proto = out.File
	file_milestones_proto_rawDesc = nil
	file_milestones_proto_goTypes = nil
	file_milestones_proto_depIdxs = nil
}
