// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.26.1
// source: personal_events.proto

package genproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PersonalEventsCreateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type    string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Title   string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Date    string `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	Preview string `protobuf:"bytes,5,opt,name=preview,proto3" json:"preview,omitempty"`
}

func (x *PersonalEventsCreateReq) Reset() {
	*x = PersonalEventsCreateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_personal_events_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PersonalEventsCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonalEventsCreateReq) ProtoMessage() {}

func (x *PersonalEventsCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_personal_events_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonalEventsCreateReq.ProtoReflect.Descriptor instead.
func (*PersonalEventsCreateReq) Descriptor() ([]byte, []int) {
	return file_personal_events_proto_rawDescGZIP(), []int{0}
}

func (x *PersonalEventsCreateReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PersonalEventsCreateReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PersonalEventsCreateReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PersonalEventsCreateReq) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *PersonalEventsCreateReq) GetPreview() string {
	if x != nil {
		return x.Preview
	}
	return ""
}

type PersonalEventsUpdateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title   string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Preview string `protobuf:"bytes,3,opt,name=preview,proto3" json:"preview,omitempty"`
}

func (x *PersonalEventsUpdateReq) Reset() {
	*x = PersonalEventsUpdateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_personal_events_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PersonalEventsUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonalEventsUpdateReq) ProtoMessage() {}

func (x *PersonalEventsUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_personal_events_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonalEventsUpdateReq.ProtoReflect.Descriptor instead.
func (*PersonalEventsUpdateReq) Descriptor() ([]byte, []int) {
	return file_personal_events_proto_rawDescGZIP(), []int{1}
}

func (x *PersonalEventsUpdateReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PersonalEventsUpdateReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PersonalEventsUpdateReq) GetPreview() string {
	if x != nil {
		return x.Preview
	}
	return ""
}

type PersonalEventsRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId  string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type    string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Title   string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Date    string `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`
	Preview string `protobuf:"bytes,6,opt,name=preview,proto3" json:"preview,omitempty"`
}

func (x *PersonalEventsRes) Reset() {
	*x = PersonalEventsRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_personal_events_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PersonalEventsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonalEventsRes) ProtoMessage() {}

func (x *PersonalEventsRes) ProtoReflect() protoreflect.Message {
	mi := &file_personal_events_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonalEventsRes.ProtoReflect.Descriptor instead.
func (*PersonalEventsRes) Descriptor() ([]byte, []int) {
	return file_personal_events_proto_rawDescGZIP(), []int{2}
}

func (x *PersonalEventsRes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PersonalEventsRes) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PersonalEventsRes) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PersonalEventsRes) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PersonalEventsRes) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *PersonalEventsRes) GetPreview() string {
	if x != nil {
		return x.Preview
	}
	return ""
}

type PersonalEventsGetByIdRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Event *PersonalEventsRes `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
}

func (x *PersonalEventsGetByIdRes) Reset() {
	*x = PersonalEventsGetByIdRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_personal_events_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PersonalEventsGetByIdRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonalEventsGetByIdRes) ProtoMessage() {}

func (x *PersonalEventsGetByIdRes) ProtoReflect() protoreflect.Message {
	mi := &file_personal_events_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonalEventsGetByIdRes.ProtoReflect.Descriptor instead.
func (*PersonalEventsGetByIdRes) Descriptor() ([]byte, []int) {
	return file_personal_events_proto_rawDescGZIP(), []int{3}
}

func (x *PersonalEventsGetByIdRes) GetEvent() *PersonalEventsRes {
	if x != nil {
		return x.Event
	}
	return nil
}

type PersonalEventsGetAllRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Events []*PersonalEventsRes `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	Count  int32                `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *PersonalEventsGetAllRes) Reset() {
	*x = PersonalEventsGetAllRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_personal_events_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PersonalEventsGetAllRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonalEventsGetAllRes) ProtoMessage() {}

func (x *PersonalEventsGetAllRes) ProtoReflect() protoreflect.Message {
	mi := &file_personal_events_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonalEventsGetAllRes.ProtoReflect.Descriptor instead.
func (*PersonalEventsGetAllRes) Descriptor() ([]byte, []int) {
	return file_personal_events_proto_rawDescGZIP(), []int{4}
}

func (x *PersonalEventsGetAllRes) GetEvents() []*PersonalEventsRes {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *PersonalEventsGetAllRes) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type PersonalEventsGetAllReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string  `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Date   string  `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Type   string  `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Filter *Filter `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
}

func (x *PersonalEventsGetAllReq) Reset() {
	*x = PersonalEventsGetAllReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_personal_events_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PersonalEventsGetAllReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonalEventsGetAllReq) ProtoMessage() {}

func (x *PersonalEventsGetAllReq) ProtoReflect() protoreflect.Message {
	mi := &file_personal_events_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonalEventsGetAllReq.ProtoReflect.Descriptor instead.
func (*PersonalEventsGetAllReq) Descriptor() ([]byte, []int) {
	return file_personal_events_proto_rawDescGZIP(), []int{5}
}

func (x *PersonalEventsGetAllReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PersonalEventsGetAllReq) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *PersonalEventsGetAllReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PersonalEventsGetAllReq) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

var File_personal_events_proto protoreflect.FileDescriptor

var file_personal_events_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x63, 0x61,
	0x70, 0x73, 0x75, 0x6c, 0x65, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x8a, 0x01, 0x0a, 0x17, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x65, 0x76, 0x69, 0x65,
	0x77, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77,
	0x22, 0x59, 0x0a, 0x17, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x22, 0x94, 0x01, 0x0a, 0x11,
	0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65,
	0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x65, 0x76,
	0x69, 0x65, 0x77, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x65, 0x76, 0x69,
	0x65, 0x77, 0x22, 0x51, 0x0a, 0x18, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x73, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x12, 0x35,
	0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e,
	0x74, 0x69, 0x6d, 0x65, 0x5f, 0x63, 0x61, 0x70, 0x73, 0x75, 0x6c, 0x65, 0x2e, 0x50, 0x65, 0x72,
	0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x52, 0x05,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x68, 0x0a, 0x17, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61,
	0x6c, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73,
	0x12, 0x37, 0x0a, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1f, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x63, 0x61, 0x70, 0x73, 0x75, 0x6c, 0x65, 0x2e,
	0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65,
	0x73, 0x52, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22,
	0x88, 0x01, 0x0a, 0x17, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x73, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x2c, 0x0a, 0x06,
	0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x74,
	0x69, 0x6d, 0x65, 0x5f, 0x63, 0x61, 0x70, 0x73, 0x75, 0x6c, 0x65, 0x2e, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x32, 0xec, 0x02, 0x0a, 0x15, 0x50,
	0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x3d, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x1f,
	0x2e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x63, 0x61, 0x70, 0x73, 0x75, 0x6c, 0x65, 0x2e, 0x50, 0x65,
	0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x1a,
	0x12, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x63, 0x61, 0x70, 0x73, 0x75, 0x6c, 0x65, 0x2e, 0x56,
	0x6f, 0x69, 0x64, 0x12, 0x45, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x12, 0x12,
	0x2e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x63, 0x61, 0x70, 0x73, 0x75, 0x6c, 0x65, 0x2e, 0x42, 0x79,
	0x49, 0x64, 0x1a, 0x26, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x63, 0x61, 0x70, 0x73, 0x75, 0x6c,
	0x65, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73,
	0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x12, 0x56, 0x0a, 0x06, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x6c, 0x12, 0x25, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x63, 0x61, 0x70, 0x73,
	0x75, 0x6c, 0x65, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x73, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x25, 0x2e, 0x74, 0x69,
	0x6d, 0x65, 0x5f, 0x63, 0x61, 0x70, 0x73, 0x75, 0x6c, 0x65, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f,
	0x6e, 0x61, 0x6c, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52,
	0x65, 0x73, 0x12, 0x43, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x25, 0x2e, 0x74,
	0x69, 0x6d, 0x65, 0x5f, 0x63, 0x61, 0x70, 0x73, 0x75, 0x6c, 0x65, 0x2e, 0x50, 0x65, 0x72, 0x73,
	0x6f, 0x6e, 0x61, 0x6c, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x63, 0x61, 0x70, 0x73, 0x75,
	0x6c, 0x65, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x12, 0x30, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x12, 0x12, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x63, 0x61, 0x70, 0x73, 0x75, 0x6c, 0x65,
	0x2e, 0x42, 0x79, 0x49, 0x64, 0x1a, 0x12, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x63, 0x61, 0x70,
	0x73, 0x75, 0x6c, 0x65, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x42, 0x0b, 0x5a, 0x09, 0x67, 0x65, 0x6e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_personal_events_proto_rawDescOnce sync.Once
	file_personal_events_proto_rawDescData = file_personal_events_proto_rawDesc
)

func file_personal_events_proto_rawDescGZIP() []byte {
	file_personal_events_proto_rawDescOnce.Do(func() {
		file_personal_events_proto_rawDescData = protoimpl.X.CompressGZIP(file_personal_events_proto_rawDescData)
	})
	return file_personal_events_proto_rawDescData
}

var file_personal_events_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_personal_events_proto_goTypes = []interface{}{
	(*PersonalEventsCreateReq)(nil),  // 0: time_capsule.PersonalEventsCreateReq
	(*PersonalEventsUpdateReq)(nil),  // 1: time_capsule.PersonalEventsUpdateReq
	(*PersonalEventsRes)(nil),        // 2: time_capsule.PersonalEventsRes
	(*PersonalEventsGetByIdRes)(nil), // 3: time_capsule.PersonalEventsGetByIdRes
	(*PersonalEventsGetAllRes)(nil),  // 4: time_capsule.PersonalEventsGetAllRes
	(*PersonalEventsGetAllReq)(nil),  // 5: time_capsule.PersonalEventsGetAllReq
	(*Filter)(nil),                   // 6: time_capsule.Filter
	(*ById)(nil),                     // 7: time_capsule.ById
	(*Void)(nil),                     // 8: time_capsule.Void
}
var file_personal_events_proto_depIdxs = []int32{
	2, // 0: time_capsule.PersonalEventsGetByIdRes.event:type_name -> time_capsule.PersonalEventsRes
	2, // 1: time_capsule.PersonalEventsGetAllRes.events:type_name -> time_capsule.PersonalEventsRes
	6, // 2: time_capsule.PersonalEventsGetAllReq.filter:type_name -> time_capsule.Filter
	2, // 3: time_capsule.PersonalEventsService.Create:input_type -> time_capsule.PersonalEventsRes
	7, // 4: time_capsule.PersonalEventsService.GetById:input_type -> time_capsule.ById
	5, // 5: time_capsule.PersonalEventsService.GetAll:input_type -> time_capsule.PersonalEventsGetAllReq
	1, // 6: time_capsule.PersonalEventsService.Update:input_type -> time_capsule.PersonalEventsUpdateReq
	7, // 7: time_capsule.PersonalEventsService.Delete:input_type -> time_capsule.ById
	8, // 8: time_capsule.PersonalEventsService.Create:output_type -> time_capsule.Void
	3, // 9: time_capsule.PersonalEventsService.GetById:output_type -> time_capsule.PersonalEventsGetByIdRes
	4, // 10: time_capsule.PersonalEventsService.GetAll:output_type -> time_capsule.PersonalEventsGetAllRes
	8, // 11: time_capsule.PersonalEventsService.Update:output_type -> time_capsule.Void
	8, // 12: time_capsule.PersonalEventsService.Delete:output_type -> time_capsule.Void
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_personal_events_proto_init() }
func file_personal_events_proto_init() {
	if File_personal_events_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_personal_events_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PersonalEventsCreateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_personal_events_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PersonalEventsUpdateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_personal_events_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PersonalEventsRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_personal_events_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PersonalEventsGetByIdRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_personal_events_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PersonalEventsGetAllRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_personal_events_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PersonalEventsGetAllReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_personal_events_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_personal_events_proto_goTypes,
		DependencyIndexes: file_personal_events_proto_depIdxs,
		MessageInfos:      file_personal_events_proto_msgTypes,
	}.Build()
	File_personal_events_proto = out.File
	file_personal_events_proto_rawDesc = nil
	file_personal_events_proto_goTypes = nil
	file_personal_events_proto_depIdxs = nil
}
