DROP TYPE IF EXISTS privacy_type CASCADE;

DROP TYPE IF EXISTS media_type CASCADE;

DROP TYPE IF EXISTS theme_type CASCADE;

DROP TABLE IF EXISTS users CASCADE;

DROP TABLE IF EXISTS memories CASCADE;

DROP TABLE IF EXISTS medias CASCADE;

DROP TABLE IF EXISTS comments CASCADE;

DROP TABLE IF EXISTS shared_memories CASCADE;

DROP TABLE IF EXISTS custom_events CASCADE;

DROP TABLE IF EXISTS milestones CASCADE;